#!/usr/bin/env python

import sh

lang_command = sh.Command("/home/iman/Applications/xkblayout-state/xkblayout-state")
symbol = lang_command("print", "%s")


if symbol == "ir":
	symbol = "FA"
elif symbol == "us":
	symbol = "EN" 
else :
	symbol = "ERR"

seprator = '<span foreground="#888">%s</span>' % "|"

print symbol, seprator